### ISSUE TITLE
svg2tikz cannot work in Inkscape version >= 1.0 on MacOS

### ISSUE THREAD

**Issue by wuxiaoqiang12** [xyz2tex/svg2tikz#53]
Hi, I want use this extension to convert svg picture to tikz code. I run this extension on MacOS 10.15.7 in Inkscape 1.0 and 1.0.1. I got error like that:
```
tikz_export.py:645: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  parser = self.OptionParser
Traceback (most recent call last):
  File "tikz_export.py", line 1478, in <module>
    main_inkscape()
  File "tikz_export.py", line 1461, in main_inkscape
    effect = TikZPathExporter(inkscape_mode=True)
  File "tikz_export.py", line 629, in __init__
    self._set_up_options()
  File "tikz_export.py", line 646, in _set_up_options
    parser.set_defaults(codeoutput='standalone', crop=False, clipboard=False,
AttributeError: 'TikZPathExporter' object has no attribute 'set_defaults'
```
I don't know what should I do.

**Comment by kjellmf** [comment]
svg2tikz is unfortunately not compatible with Inkscape 1.x. See #42 for more information

**Comment by kjellmf** [comment]
Fixed in 8e56b57
