### ISSUE TITLE
Regression: command line tool broken after 8e56b57

### ISSUE THREAD

**Issue by miccoli** [xyz2tex/svg2tikz#62]
After commit 8e56b57 the command line tool (stand-alone python) is broken. In fact it is impossible to load `svg2tikz.extensions.tikz_export.TikZPathExporter`
```
>>> import svg2tikz.extensions.tikz_export
>>> svg2tikz.extensions.tikz_export.TikZPathExporter(inkscape_mode=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/miccoli/src/oss/svg2tikz/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'
```

**Comment by kjellmf** [comment]
Sorry about that.  The bundled inkexlib is no longer compatible with inkscape 1.x. Not quite sure what to do about that. I can probably find a workaround but then I'll need to better understand the new extension code in inkscape 1.x. It has changed quite a bit since I first wrote svg2tikz.

**Comment by miccoli** [comment]
I have no idea of the internal workings of inkscape, but maybe you can just bundle the `inkex` directory from <https://gitlab.com/inkscape/extensions>. As a quick check I run
```
$ git clone https://gitlab.com/inkscape/extensions.git
Cloning into 'extensions'...
remote: Enumerating objects: 19697, done.
remote: Counting objects: 100% (1465/1465), done.
remote: Compressing objects: 100% (559/559), done.
remote: Total 19697 (delta 929), reused 1438 (delta 905), pack-reused 18232
Receiving objects: 100% (19697/19697), 11.50 MiB | 17.14 MiB/s, done.
Resolving deltas: 100% (14744/14744), done.
$ pip install -q lxml cssselect
$ PYTHONPATH=./extensions python
Python 3.9.5 (default, May 28 2021, 23:12:16) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import inkex
>>> import simplestyle
>>> import simplepath
>>> 
```
and at least the modules are correctly loaded... Of course some work for testing and packaging is needed.

I noticed that `simplepath` and `simplestyle` reside in `inkex/deprecated-simple` which is not loadable as a package, but `import inkex` tweaks `sys.path` so that both become loadable as root modules.

**Comment by kjellmf** [comment]
Bundling the inkex directory is probably the easiest solution. I will investigate

**Comment by eelcovv** [comment]
Running into the same error. Any progress fixing this error?

**Comment by miccoli** [comment]
> Running into the same error. Any progress fixing this error?

@eelcovv if you only need to run the CLI you can simply checkout 7a9959c and build and install from that. At leas this quick walk around worked for me.

**Comment by kjellmf** [comment]
I have not worked on this yet. The new inkex module is more complex than the old one. Extracting only the code needed was more complicated than anticipated.

**Comment by ashutoshbsathe** [comment]
> > Running into the same error. Any progress fixing this error?
> 
> @eelcovv if you only need to run the CLI you can simply checkout [7a9959c](https://github.com/xyz2tex/svg2tikz/commit/7a9959c295e1ed73e543474c6f3679d04cebc9e9) and build and install from that. At leas this quick walk around worked for me.

I checked out that commit and it still doesn't convert any text in my SVG. My SVGs are exported from draw.io. Any pointers ?

**Comment by ktali** [comment]
> > > Running into the same error. Any progress fixing this error?
> > 
> > 
> > @eelcovv if you only need to run the CLI you can simply checkout [7a9959c](https://github.com/xyz2tex/svg2tikz/commit/7a9959c295e1ed73e543474c6f3679d04cebc9e9) and build and install from that. At leas this quick walk around worked for me.
> 
> I checked out that commit and it still doesn't convert any text in my SVG. My SVGs are exported from draw.io. Any pointers ?

@ashutoshbsathe , your issue should be fixed if you switch off "Word Wrap" and "Formatted Text" on your labels.
More information here: https://www.diagrams.net/doc/faq/svg-export-text-problems

**Comment by ldevillez** [comment]
Should be fixed by #68
