### ISSUE TITLE
Importing module fails in Pyzo

### ISSUE THREAD

**Issue by ysalmon** [xyz2tex/svg2tikz#144]
**Describe the bug**
On ``import svg2tikz``, I get ``AttributeError: 'FileWrapper' object has no attribute 'buffer'`` on line 1337 in ``tikz_export.py``.

**Setup:**
 - Mode: python package, python 3.10.12
 - SVG2TikZ version: today's master
 - OS version: KUbuntu 22.04

**To Reproduce**
Import the module.

**Additional information**

Seems to work when replacing ``def run(self, args=None, output=sys.stdout.buffer):`` with ``def run(self, args=None, output=sys.stdout):``.

**Comment by ldevillez** [comment]
Hello @ysalmon, 
I cannot reproduce the problem on my side.
Can you install svg2tikz in a venv, try to import it and post the result of pip freeze ?

**Comment by ysalmon** [comment]
I could not reproduce it either in my terminal.

Upon further investigation, it only happens when doing the import from the console in Pyzo, and only with the master.

pip freeze gives
```
pip freeze
cssselect==1.2.0
inkex==1.3.0
lxml==4.9.3
numpy==1.26.0
packaging==23.2
Pillow==10.0.1
pycairo==1.25.0
PyGObject==3.46.0
pyparsing==3.1.1
pyserial==3.5
scour==0.37
six==1.16.0
svg2tikz @ file:///tmp/svg2tikz
```

Importing works fine with the 2.1.0 release, even in Pyzo. So there is something peculiar.

**Comment by ldevillez** [comment]
Hello @ysalmon, could you try PR #151 ?

**Comment by ysalmon** [comment]
Just did it ; it correctly shows a red warning message about redirecting output to None, but does not fail importing.

**Comment by ldevillez** [comment]
Fixed for you then ? :)

**Comment by ysalmon** [comment]
Yes !
